### ISSUE TITLE
2021 Census Data?

### ISSUE THREAD

**Issue by nathannli** [andrewjdyck/statscanpy#1]
Wondering how portable this will be when 2021 census data releases throughout this year?

**Comment by andrewjdyck** [comment]
Statistics canada has their Census data services split between the years so, no, this package will not work for 2021 census releases. The implementation here utilizes the 2016 census web data services (WDS) documented here (https://www12.statcan.gc.ca/wds-sdw/cpr2016-eng.cfm). If one wanted to include data from the 2021 census release here, one would need to look through the documentation for 2021 here: https://www12.statcan.gc.ca/wds-sdw/2021profile-profil2021-eng.cfm, and then adapt this package to allow the user to distinguish between which census release they wanted to use - either 2016 or 2021.
